- index.yml
> Build dharmit/pipeline-scanner with container pipeline

- index.yml
> Fix typo in index.yml for pipeline-scanner image

- index.yml
Added index entries for software collections containers. Few containers have not been included as its s2itool based.
This is based on PRs for cccp.yml files against sclo repositories below
https://github.com/sclorg/mysql-container/pull/158
https://github.com/sclorg/nginx-container/pull/3
https://github.com/sclorg/ror-container/pull/3
https://github.com/sclorg/thermostat-container/pull/3
https://github.com/sclorg/devtoolset-container/pull/4
https://github.com/sclorg/mariadb-container/pull/5
> Added entries for sclo containers.

- index.yml
Based on PR sent against CentOS Dockerfiles 
https://github.com/CentOS/CentOS-Dockerfiles/pull/73/files
> Added index entries for build able centos dockerfiles containers.

- index.yml
Signed-off-by: hchiramm <hchiramm@redhat.com>
> Adding centos storage sig container pipeline

- index.yml
* depends-on parameter got removed while fixing merge conflicts added the same
> Fixed depends on for postgresql 9.6

- index.yml
> Che dockerfiles

- index.yml
* Added entry for container-pipeline-service images
* cccp-build - used as build environment
* cccp-test  - used as test environment
* cccp-delivery - used as delivery environment
* mail-server - used for sending all the mail notifications from notify_user beanstalk tube
> Added entries for container-pipeline-service

- index.d/bamachrn.yml
* For Demo purpose changed target file name and path
> Changed targetfile name and path

- index.d/bamachrn.yml
* Changed desired tag to demo form latest
> Changed image tag from latest to demo

- index.d/bamachrn.yml
* Changed desired tag for demo
> Changed the desired tag to release

- index.d/bamachrn.yml
* Added three entries for mattermost-app, mattermost-db, mattermost-web
> Added mattermost entries to pipeline

- index.d/centos.yml
* Added centos/postgres to pipeline with latest tag
> Added centos/postgres entry for index

- index.d/openshift.yml
This is for the purpose of building openshift origin containers through pipeline
> Added entries for origin containers.

- index.d/centos.yml
Corrected image name from centos-base to centos and added another entry for centos7 tag from the same source.
> Modified entries for centos base image on container pipeline.

- index.d/eclipse.yml
> index.d entries for Eclipse Che container images

- index.d/pipeline-images.yml
> Modify pipeline-scanner image's entry in index.d

- index.d/eclipse.yml
ping @bamachrn can you help merge this simple one?
> Eclipse python 3 stack now based off SCL instead of EPEL

- index.d/openshift.yml
This is until the tag problem in origin can be sorted out.
> Altered origin desired-tags to latest.

- index.d/bamachrn.yml
* Added desired-tag parameter to get CI for index passed for whole index
> Added desired-tag:latest to mattermost entries

- index.d/openshift.yml
This is for purpose of properly building origin 1.2.1 containers
and in prepration for origin 1.3.
> Changed desired-tag to 1.2.1 on origin and added it to bamachrn.

- index.d/eclipse.yml
> Add entry to build che-server using pipeline

- index.d/bamachrn.yml
* Removed python demo entry for pycon demo
> Removed python project for demo

- .gitignore
- index.d/jboss.yml
This is for the purpose of building keycloak containers in
container pipeline. Also corrected error in gitignore which
ignore newly added yml files in index.d.
> Added index entries for keycloak and corrected gitignore.

- index.d/openshift.yml
- index.d/sclo.yml
These mostly include the sclorg containers for s2i.
> Added entries for more functional sclo containers.

- index.d/cockpit.yml
As initial entry, we have the cockpit kubernetes container
as its required by atomic registry.
> Added cockpit.yml to track cockpit containers

- index.d/cockpit.yml
This is for building the cockpit workstation containers.
> Added cockpit ws containers.

- index.d/sclo.yml
This updates the remaining sclorg containers which currently build from my fork of the repositories, to build directly from upstream repositories.
> Updated new sclorg container entries to build from upstream.

- index.d/eclipse.yml
ping @kbsingh @mohammedzee1000
> Temporarily commenting che-server entry

- index.d/openshift.yml
This is keeping with the discussion with @tdawson about
delivering the latest release of openshift containers.
> Bumped up the origin container version to v1.3.1 and latest.

- index.d/centos.yml
This is a temporary measure until multiple desired-tag support is added.
> Added entries for alternate centos7 tags and centos6 container.

- index.d/dharmit.yml
> Build basic maven image in pipeline

- index.d/centos.yml
Currently build from my fork
Upstream PR :  https://github.com/CentOS/CentOS-Dockerfiles/pull/108
> Added pgweb container to the container index.

- index.d/jboss.yml
One of dependencies, jboss wildfly adapter needs the
other tag.
> Updated jboss wildfly entry for another tag

- index.d/dharmit.yml
ping @navidshaikh @mohammedzee1000
> Fix minor typo in job-id

- index.d/dharmit.yml
> Build Vertx stack on CentOS Container Pipeline

- index.d/dharmit.yml
- index.d/pipeline-images.yml
This can be merged after merging pipeline service [PR #130](https://github.com/CentOS/container-pipeline-service/pull/130).
> Adds atomic scanner for pip, npm and gem to index

- index.d/dharmit.yml
- index.d/pipeline-images.yml
@mohammedzee1000 @bamachrn can you please review and help get this one merged? Sorry about the error on my part earlier. :disappointed:
> Move scanner entry to pipeline-images.yml

- README.rst
- whattomerge.md
Added important guidelines related to ci warnings to both merge guide and readme.
> Applied changes to merge guide and readme.

- index.d/che-stacks.yml
- index.d/dharmit.yml
ping @mohammedzee1000 @bamachrn
> Move Vert.X container image to che-stacks namespace

- index.d/dharmit.yml
ping @bamachrn @kbsingh can you help merge this one please?
> Atomic scanner to list rpm packages

- index.d/che-stacks.yml
@bamachrn @kbsingh can you please help merge this?
> Vertx image now builds off upstream eclipse repo

- index.d/dries.yml
Test of the container pipeline with some help of Karanbir.
> Test container pipeline with a small test container

- index.d/pipeline-images.yml
ping @bamachrn @kbsingh @mohammedzee1000 
Please help merge this PR.
> Add container capabilities scanner to the index

- index.d/sclo.yml
Changed notification emails for sclo containers that somehow escaped
last time. Used sed to ensure no such escapes happen this time.
> Updated notification emails for sclo containers missed out.

- index.d/datamodel.yml
Fixes this issue - https://github.com/containscafeine/data-model/issues/12
> Update notifiation email for container builds

- index.d/che-stacks.yml
ping @mohammedzee1000 @kbsingh
> Add che-stacks/springboot entry

- index.d/kbsingh.yml
setting up mysql-proxy to build
> add mysql-proxy

- index.d/fabric8.yml
Add a project and namespaec for fabric8/ 
as the first step, lets start with the nginx custom build we need to consolidate here.
> add fabric8 project

- index.d/che-stacks.yml
> Modify Spring Boot entry to use upstream repo

- index.d/dharmit.yml
Containerizing freegeoip project to use CentOS base image
> Add container-index entry for fiorix/freegeoip project

- index.d/kbsingh.yml
Start working on the gogs container, i will aim to have this working for local docker runs but also for openshift workloads
> add gogs container

- index.d/kbsingh.yml
setup the stub for zabbix-agent and get builds going, while I workout how to get this working and configured in openshift
> add zabbix-agent

- index.d/postgresql.yml
They will be available from my repo until we can get them pushed
to upstream repositories.
> Added entries for upstream containers for postgresql.

- index.d/che-stacks.yml
> Build WildFly Swarm image on CentOS Pipeline

- index.d/dharmit.yml
[NSQ](https://nsq.io) is a realtime distributed messaging system developed in Golang. This PR helps create its otherwise Alpine based container image on top of CentOS.
> Build NSQ images based on CentOS through the Pipeline

- index.d/che-stacks.yml
ping @mohammedzee1000 @bamachrn @kbsingh
> Add CentOS based nodejs4 stack to default assembly

- index.d/dharmit.yml
ping @bamachrn @mohammedzee1000 @kbsingh
> Add CentOS based minimal stack with only git

- index.d/fabric8.yml
we need to version the nginx build
> Add tag nginx

- index.d/pipeline-images.yml
Now that scanner's been merged into upstream, time to change its namespace.
> Update container capabilities scanner namespace

- index.d/pipeline-images.yml
> Point misc-package-updates to use upstream repo

- index.d/centos.yml
This adds sentry project to the container index under centos namespace.
> Added sentry container to container-index

- index.d/openshift.yml
- index.d/projectatomic.yml
- index.d/sclo.yml
This PR adds entries for playbook to image as well as updates notify-email.
> Updated notify email for atomic registry image and added playbook s2i

- index.d/che-stacks.yml
- index.d/dharmit.yml
ping @mohammedzee1000 @bamachrn
> Move centos-go entry to che-stacks namespace

- index.d/dharmit.yml
- index.d/eclipse.yml
- index.d/openshift.yml
we seem to have some stale entries, @mohammedzee1000 can you please track down what happened to these images and get this resolved with @dharmit and with the sclo guys.
> Trim stale

- index.d/library.yml
Will first require refactor of https://github.com/CentOS/container-pipeline-service/pull/275
> Added library images to container index.

- index.d/dharmit.yml
ping @bamachrn @mohammedzee1000 
This is with regards to adding language/framework images to r.c.o
> Add golang 1.6 and 1.7 images

- index.d/pipeline-images.yml
> Added entry for building registry UI container.

- index.d/dharmit.yml
Add more language images to the index. ping @mohammedzee1000 @bamachrn
> Add python 2.7 and 3.5 images

- index.d/dharmit.yml
ping @bamachrn this is for the talk I'm going to give.
> Add digitalocean-compass to index

- index.d/che-stacks.yml
That's the case since https://github.com/eclipse/che-dockerfiles/pull/127
> centos-stack-base is all che-stacks base image

- index.d/che-stacks.yml
> Add CentOS based DotNet 2.0 stack to default assembly

- index.d/dharmit.yml
Also, remove digitalocean-compass image since it's not needed anymore
ping @mohammedzee1000 @bamachrn
> Add dotnet20 image to index

- index.d/che-stacks.yml
Minor change in the index entry. PTAL @bamachrn @mohammedzee1000
> Change base image for che-stacks dotnet image

- index.d/arrfab.yml
First attempt to get my first used container built/delivered through registry.centos.org
> Adding nanoc to the containers list

- index.d/pipeline-images.yml
Removed the mail-server entry as this has to be updated to proper value in the restructured code base
> Removed mail-server entry for updating it to proper value

- index.d/dotnet.yml
These are CentOS mirror images of
registry.access.redhat.com/dotnet/dotnet-20{,-runtime}-rhel7
> Add .NET Core 2.0 images.

- index.d/dotnet.yml
Depends on https://github.com/redhat-developer/dotnet-jenkins-slave/pull/5
CC @jerboaa
> Add .NET Core 2.0 Jenkins slave image

- index.d/dharmit.yml
- index.d/nats-io.yml
> Build gnatsd on CentOS Container Pipeline

- index.d/mattermost.yml
delete unnecessory jobs and move mattermost from jfchevrette/mattermost-openshift to rhdt/mattermost-openshift
> delete unnecessary jobs + switch mattermost-openshift

- index.d/kbsingh.yml
A PoC for what a PR might look like that uses the pre-build script. Let me know what / how to edit the git-url destination, its currently set wrongly to the prebuild-source repo.
> create a prebuild test

- index.d/user-cont.yml
Let me know if I can provide any help.
> add tools image of gh.com/container-images

- index.d/fabric8-hdd.yml
Signed-off-by: anmolbabu <anmolbudugutta@gmail.com>
> Change fabric8-hdd desired tag to latest

- index.d/dharmit.yml
> CentOS based beanstalkd image

- index.d/projectatomic.yml
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>
> projectatomic: change location for CRI-O

- index.d/nshaikh.yml
Added a container in pre-prod branch of index which fails by installing a non existent package in Dockerfile.
> Adds a container which fails to build

- README.md
> Updating readme with information based on changed to service.

- index.d/centos.yml
> Adding centos atomic base image to the container index.

- index.d/nshaikh.yml
To test out different scenarios in CI.
> Adds a failing Dockerfile for build failure test

- index.d/fabric8-services.yml
Trying to build fabric8-wit image in pipeline using the pre-build script. PTAL and suggest for any changes that are required @mohammedzee1000 @bamachrn
> Build fabric8-wit image in pipeline

- index.d/container-examples.yml
changed notification email & added a new tag/build for starter-systemd.
> container-examples update

- index.d/openshift.yml
Adds build parameters to build openshift/image-inspector container.
> Adds openshift/image-inspector container

- index.d/che-stacks.yml
This is based on discussion with @l0rd to change the notification email for che-stacks images.
> Change notification email for che-stacks entries

- index.d/pipeline-images.yml
This changeset indexes atomic scanner container namely
scanner-analytics-integration on build service.
> Adds scanner-analytics-integration atomic scanner container

- index.d/nshaikh.yml
Relocated the git repository to a different location, this changeset
reflects the changes on indexing details.
> Updates git-url for a fail-test-container

- index.d/nshaikh.yml
This is mostly going to be used for testing.
> Adds minimal golang hello world container based on scratch

- index.d/dmick.yml
Signed-off-by: Dan Mick <dan.mick@redhat.com>
> Add a personal index file

- index.d/mattermost.yml
add mattermost v4.4, v4.5 and v4.6 images to r.c.o
> add mattermost v4.4, v4.5 and v4.6 images

- index.d/centos.yml
This builds https://github.com/CentOS/CentOS-Dockerfiles/pull/166
> build sentry-sso

- index.d/cdrage.yml
> Add reg containers

- index.d/centos.yml
> Fix build-context for centos/varnish-4-centos7 container

- index.d/cdrage.yml
- index.d/pipeline-images.yml
The entries for reg container in index are currently
broken. Taking them out of picture to unblock other
containers.
> Temporarily removing currently broken index entries.

- index.d/cdrage.yml
- index.d/pipeline-images.yml
Readds the registry UI now that the upstream repo has cccp.yaml
> Readd cdrage/reg

- index.d/mattermost.yml
this will add mattermost v4.7.0 image into the index
> add mattermost v4.7.0

- index.d/centos.yml
- index.d/kbsingh.yml
Moving the kbsingh/centos7-atomic to centos/centos7-atomic
> Move atomic container from kbsingh to centos namespace

- index.d/mohammedzee1000.yml
- index.d/postgresql.yml
> Removing older versions of postgresql containers.

- index.d/minishift.yml
Related to https://github.com/minishift/minishift/issues/201
> Add dnsmasq service container for Minishift

- index.d/centos.yml
- index.d/fabric8.yml
- index.d/projectatomic.yml
For testing on pre-prod environment.
> Indexes fabric8.yml and projectatomic.yml projects for testing

- index.d/mattermost.yml
removing the older version (4.1)
adding the latest version with PCP
> change v4.1 slot to build v4.7+pcp

- .gitignore
- index.d/minishift.yaml
> Adding back minishift dnsmasq container.

- index.d/dharmit.yaml
ping @bamachrn this is for the Jenkins slave that we're creating for OpenShift task
> Build ccp-openshift-slave image on pipeline

- index.d/mattermost.yaml
change the repo URLs to fetch source from rhdt namespace
+ reorder and change matterircd slot to build mm-push-proxy
> change URL to rhdt namespace + change matterircd slot to build mm-pp

- index.d/mattermost.yaml
> update mattermost-team slots to build new version

- index.d/minishift.yaml
> Update minishift dnsmasq container definition location

- index.d/gbraad.yaml
Initial version of a minishift build container for use in CI
> Add definition for minishift build

- index.d/nshaikh.yml
Commenting out image that's not based on CentOS base image.
> Remove non-CentOS based container

- index.d/openshift.yaml
This PR adds openshift origin 3.9 to the container index.
> Adding openshift origin 3.9 containers to the container index.

- index.d/mattermost.yaml
change : 
matterbridge 1.7.1 slot to  1.10.1
mattermost-team 4.5 slot to 4.10-PCP
> upgrade versions of matterbridge & mattermost-team

- index.d/mattermost.yaml
- Add entry for Mattermost team release 5.0
- Remove index entry for oldest image: v4.7
> Add entry for Mattermost team release 5.0

- index.d/pipeline-images.yaml
- Updates the git-url and git-path for ccp-openshift-scan container
- Updates the git-url and git-path for ccp-openshift-slave container
> Update ccp-openshift containers

- index.d/mattermost.yaml
Changeset:
https://github.com/42wim/matterbridge/releases/tag/v1.11.2
https://github.com/42wim/matterbridge/releases/tag/v1.11.1
Source dir: 
https://github.com/rhdt/matterbridge/tree/master/1.11.2
> Add Matterbridge v1.11.2

- index.d/navidshaikh.yaml
> Removes notification feature ccp-openshift-slave testing container

- README.md
The readme should explicitly mention the conditions for adding image
to index. Also, correcting the levels of the headings.
> Updating readme with conditions for adding image and fixing headings.

- index.d/nshaikh.yaml
* removes nshaikh-go-helloworld image from CI as it is not centos based image
> Remove non centos based image from CI

- .gitignore
- index.d/bamachrn.yaml
Added one entry to index to test out pre-prod
> Added bamachrn-python to pre-prod

- index.d/pipeline-images.yaml
Adding slave image for pre-prod
> Added slave image to pre-prod

- index.d/pipeline-images.yaml
Removing index entry as image no longer exists
> Removing missing cccp-scan-image from index.

- index.d/navidshaikh.yaml
This will server CCP readonly APIs for pipeline service.
> Adds ccp-api-server container

- index.d/centos.yaml
This PR adds entries for those projects in [CentOS-Dockerfiles](https://github.com/CentOS/CentOS-Dockerfiles) repo that are not already present in the index.
> Add entries for CentOS Dockerfiles

- index.d/navidshaikh.yaml
The slave image contains updated scanners.
> Adds entry for new-scanners tag for slave image

- README.md
This change updates the README to fix the second commit message.
> README: fix commit message example

- index.d/pipeline-images.yaml
In this PR 
* api-server image is added for pipeline.
* cccp-build, test,delivery images are removed as we are not using them any more.
> Added api-server and removed builder images

- index.d/pipeline-images.yaml
updated pipeline-images to use master branch
> Updated index for pipeline-images entries

- index.d/che-stacks.yaml
@ibuziuk @dharmit @bamachrn @dneary
> vorburger@redhat.com => mike@vorburger.ch in che-stacks.yaml

- index.d/softwarefactory-project.yaml
Initially, we will only be building a container for the DLRN API [1].
[1] - https://github.com/softwarefactory-project/DLRN
> Add softwareafactory-project to the index

- index.d/centos.yaml
- index.d/che-stacks.yaml
- index.d/cockpit.yaml
- index.d/container-examples.yaml
- index.d/dotnet.yaml
- index.d/fabric8.yaml
- index.d/gluster.yaml
- index.d/index_template.yaml
- index.d/jboss.yaml
- index.d/jfchevrette.yaml
- index.d/kbsingh.yaml
- index.d/mattermost.yaml
- index.d/mohammedzee1000.yaml
- index.d/openshift.yaml
This PR
* removed multiple dependencies from the entries
* this makes sure the image are not getting triggered multiple times, in case of centos base image update
> Remove cyclic dependency

- index.d/cockpit.yaml
- index.d/openshift.yaml
- index.d/rhsyseng.yaml
This PR is only for fixing the index format. no content change
> Fixed format for better human readability

- index.d/centos.yaml
- index.d/library.yaml
This PR on boards centos 8 images and updates the centos7 images with proper branch
> Added CentOS 8 entries under centos and library appid

- index.d/centos.yaml
This pull request removes deprecated SCL versions.
> Remove deprecated SCL versions

- index.d/dotnet.yaml
Fixes: #404
I have copied the entries from .NET Core 3.0 in the same file above, but haven't actually tested it.
cc @aslicerh
> Add .NET Core 3.1 images

- index.d/centos.yaml
This is one of the containers tested by `openshift/odo` project
https://github.com/openshift/odo/issues/4278
> Adding nodejs 12 s2i container.

- index.d/centos.yaml
- index.d/library.yaml
- index.d/pipeline-images.yaml
updated centos latest tag to point to centos8
> Centos latest update

- index.d/centos.yaml
> NodeJS-10 image has reached EOL.
