index.yml
* This entry is for getting centos base image built and pushed to registry.centos.org
* Image will be pushed with name centos/centos:latest
=> Added entries for centos base image

index.yml
This is for the purpose of testing the postresql containers
before adding to upstream.
=> Added entries for postgresql containers.

index.d/openshift.yml
This is to get the origin containers building, although we should figure out a more long term fix.
Referencing issue : https://github.com/CentOS/container-pipeline-service/issues/70
=> Temporarily made openshift's depends on into single item list.

index.d/pipeline-images.yml
This PR adds a new container image to CCCP index. The image is an atomic scanner, namely `scanner-rpm-verify`.  It checks verifies and reports the problems with installed RPM packages and their files in given image under test.
=> Adds a new scanner image to CCCP index

index.d/dharmit.yml
fix's https://github.com/CentOS/container-index/issues/57
=> change job id for centos_go to centos-go and centos_jre to centos-jre

index.d/kbsingh.yml
this re-implements the CentOS-Dockerfile nginx, in a way that it can run on an openshift platform
=> request kbsingh/openshift-nginx to build queue

cccp.yml
The template cccp.yml file should contain more information about the container pipeline
itself, and should ideally be used in all the target repositores.
=> Updated the cccp.yml file template to include more information.

index.d/mohammedzee1000.yml
This is until, we can get the container fixed for running in openshift in the upstream.
=> Build keycloak postgres with downstream changes from my fork.

index.d/dries.yml
A simple docker image that could be used to run beanstalkd
=> Add a docker image for beanstalkd

index.d/kbsingh.yml
this should result in a usable golang container with as many of the godeps installed as possible. Using the centosplus golang since its newer than the in distro one
=> add golang 1.7.4

index.d/che-stacks.yml, index.d/dharmit.yml
This container was under my namepsace earlier. For the stacks, we need to put it under `che-stacks` namepsace.
=> Move centos-git container under che-stacks namespace

index.d/mattermost.yml
This updates the mattermost-openshift definition to find version 3.7 in 3.7 folder
Version 3.7 remains the one tagged with 'latest'
=> Update mattermost-openshift to versioned tags

index.d/che-stacks.yml
Index entries were pointing to my fork of the repo and hence a rebuilt didn't happen after the merge of https://github.com/eclipse/che-dockerfiles/pull/108
@bamachrn ping.
=> Fix Che Stacks entry to point to its canonical upstream

index.d/centos.yml
as upstream is no longer maintaining it.
=> Remove sentry:8.16 from container index

index.d/cockpit.yml
* Pointed cockpit containers to get built from the upstream cockpit repo.
* replaced cockpit/ws:latest with upstream one as it is building without any errors.
* created one more entry for `cockpit/kubernetes:upstream`. this image is having build time erros so did not replace the latest built from centos-dockerfiles.
=> Added cockpit upstream container images

index.d/dharmit.yml
ping @bamachrn @mohammedzee1000 this is for the languages/framework images that we plan to add. Taking a cue from images built for Che stacks, I've prepared an image that will have basic packages installed and configurations done so that we can just build on top of it.
=> Base image to be used by other images to build on top of

index.d/che-stacks.yml
A new base image for Che stacks has been added via https://github.com/eclipse/che-dockerfiles/pull/127. This new entry corresponds to it.
=> Add CentOS base image (`centos-stack-base`) for Che stacks

index.d/che-stacks.yml
I missed making this change when I went through https://github.com/eclipse/che-dockerfiles/pull/127/ earlier.
=> Change `depends-on` for che-stacks images to sync with upstream repo

index.d/che-stacks.yml
Should be merged after https://github.com/eclipse/che-dockerfiles/pull/129 is merged
=> Build che-stacks/centos-ceylon-nodejs-dart image on registry.centos.org

index.d/dharmit.yml
`centosplus` repo's got newer version of `golang`. `1.7` -> `1.8.3`. This PR syncs image with the change.
=> Change tag and base image for golang image

index.d/dotnet.yml
Use correct image:
dotnet/dotnet-20-runtime-centos7
vs.
centos/dotnet-20-runtime-centos7
=> Fix .NET builder image dependency.

index.d/che-stacks.yml
The stack definition still pointed to @dharmit github repository
=> Fix che-stacks/centos-dotnet20 description

index.d/projectatomic.yml
They are maintained here:
https://github.com/projectatomic/atomic-system-containers/tree/master/cri-o-centos
and
https://github.com/projectatomic/atomic-system-containers/tree/master/docker-centos
=> projectatomic: Add the CRI-O and Docker system containers

index.d/centos.yml
@bamachrn @mohammedzee1000 this is half the work done. Other half would be to fork sentry repo into our namespace.
=> Remove references to rtnpro's email address from container index

index.d/fabric8-hdd.yml
Add fabric8 hdd supervisor to centos index
Signed-off-by: anmolbabu <anmolbudugutta@gmail.com>
=> Add fabric8 hdd supervisor to centos index

index.d/dotnet.yml
The notification should ideally go out to more than one person. Since it only goes out to one person, it should probably go to someone who is following the containers closely, instead of me (I am more tangentially involved).
cc @aslicerh
=> Change notification email address for dotnet images

index.d/pipeline-images.yml
At the moment it's referring to my fork because we haven't merged code in upstream master. Once this is merged and the image is built, CI check for Dockerfile linter worker containerization can happen smoothly.
ping @mohammedzee1000 @bamachrn
=> Build dockerfile linter worker image

index.d/pipeline-images.yml
This is to aid CI for https://github.com/CentOS/container-pipeline-service/pull/412. Once it's merged, we need to remove this image from index.
=> A temporary linter worker image

index.d/nshaikh.yml
Container based on scratch, with 1.55MB image size. This is to speed up build phase time for container in CI testing.
=> Adds minimal golang container for CI testing

index.d/centos.yml, index.d/kbsingh.yml
This is due to the fact that that the container
is not ready to move to centos namespace.
=> Moving atomic container to kbsingh namespace.

index.d/dotnet.yml
Instead of having me be the primary contact, send all dotnet container notifications to an alias that is read by multiple people. This lets me go on vacation without worrying that no one will see container build errors.
=> Update address for dotnet container notifications

index.d/centos.yml
Adding a build for Sentry 8.22 to extend 8.17 and 8.18 we already have. Not moving to :latest tag as yet till we can get some testing around this.
=> add an entry for sentry 8.22

index.d/centos.yml
Since Dockerfile has path references from root of directory.
=> Test updating build-context for centos/varnish-4 container

index.d/pipeline-images.yml
Adds the new registry image to pipeline-images in order to propagate the
new registry.centos.org website.
Must be merged in BEFORE https://github.com/CentOS/container-pipeline-service/pull/455
=> Adds the new registry image to the pipeline

index.d/rhsyseng.yaml
Added CentOS versions for
- Elasticsearch 
- Kibana
Versions
- 6.2.1
- 6.1.2
- 5.5.2
=> Added RHSysEng elasticsearch and kibana

index.d/centos.yml
This is to be able to test removal of repoinfo object for CentOS base images and hence see if that helps stop RPM tracking from triggering image rebuilds for base image.
=> Add two CentOS base images to pre-prod branch

index.d/eclipse.yml
This image is way outdated and keeps failing in the service. We don't have any users for it. ping @bamachrn
=> Remove eclipse-che-dev image from container-index

index.d/datamodel.yml
This image is not being used anymore by datamodel team.
ping @msrb: does this look good?
=> Remove datamodel/gremlin:1.2.0 image from index

index.d/dharmit.yaml
Initially we had 1.6 and 1.8 images building because both RPMs were available. But now, 1.6 is no longer available and 1.8 has become the default golang version in CentOS repos.
=> Remove golang 1.6 image since the RPM package is no longer available

index.d/dharmit.yaml
atomic scanner installation's failing in my OpenShift setup due to [`docker run -it`](https://github.com/CentOS/container-pipeline-service/blob/master/atomic_scanners/pipeline-scanner/Dockerfile#L3). Can't change upstream scanner for MVP so created this fork for temporary use. PTAL @bamachrn
=> Pipeline scanner for OpenShift MVP

index.d/centos.yaml
Recently the sclorg postgresql image repository embraced distgen for source generation via https://github.com/sclorg/postgresql-container/pull/203
This PR modifies the index to run a pre-build hook that generates the sources before attempting to build the images.
=> Add pre-build hook for sclorg postgresql

index.d/projectatomic.yml
Earlier there was a typo occurred while updating notify-email for projectatomic namespaced builds. `container-status-report@centos.org` is the notify-email for all the testing builds.
=> Updates notify-email for testing branch

index.d/openshift.yaml
[Upstream repo](https://github.com/openshift/jenkins/tree/master) doesn't have the `git-path`. So this doesn't need to be built anymore.
=> Jenkins 1 has been removed from upstream repo

index.d/pipeline-images.yaml
We're no longer interested in having a containerized Dockerfile lint worker. Hence removing the entries from index.
=> Remove index entries for Dockerfile linter worker

index.d/centos.yaml, index.d/library.yaml
I noticed that `registry.centos.org/centos:7` exists, but `registry.centos.org/centos:6` doesn't.  This pull request should address that.  It also adds the `7` tag to `library.yaml` to match `centos.yaml`.
=> add 6 tag for centos image

index.d/projectatomic.yml
Removing this project because it's causing Jenkins workspace to fill up in pre-prod.
=> Remove atomic registry install from pre-prod

index.d/centos.yml
One more image that's taking a lot of space. Hence removing it.
=> Remove CentOS 7 image from pre-prod

index.d/projectatomic.yaml
Atomic Registry has been deprecated.
Signed-off-by: Aaron Weitekamp <aweiteka@redhat.com>
=> remove atomic-registry-intsall

index.d/jfchevrette.yaml
I would like to add and maintain images of openshift origin clients based on centos/centos:7
=> Add jfchevrette/origin-clients images

index.d/centos.yaml
Varnish 5 image was released in RHSCL 3.1 in May 2018.
Also the repository started to use distgen for source generation via https://github.com/sclorg/varnish-container/pull/45. 
This PR modifies the index to run a pre-build hook that generates the sources before attempting to build the images. Similar to PR #311 for postgresql.
And both varnish 4 and 5 uses s2i-core as a base image (see [1] and [2]). So `depends-on` block can be cleaner.
[1] https://github.com/sclorg/varnish-container/blob/master/4/Dockerfile
[2] https://github.com/sclorg/varnish-container/blob/master/5/Dockerfile
=> Add sclorg/varnish 5 image + use prebuild script for distgen

.gitignore, cccp.yaml, index.d/index_template.yaml
It seems that the template files have been removed when they were
supposed to be renamed from .yml to .yaml. With these files re-added,
the README.md makes more sense again.
Fixes: 5ab75d6445a644515ea1f37cf58663e7a9a892c9
Signed-off-by: Niels de Vos <ndevos@redhat.com>
=> Re-add .yaml files that were removed instead of renamed

index.d/nshaikh.yaml
This container is to be used for serving as openshift-slave
and contains required scripts and binaries for building pipeline.
=> Adds ccp-openshift-slave container to index

index.d/pipeline-images.yaml
This is to build our own Jenkins image for OpenShift architecture work. It will help us have a control over adding/removing plugins in Jenkins. Also we can set proper configuration parameters wherever required and have more control.
=> Add Jenkins image for pipeline service

index.d/pipeline-images.yaml
Changing the repo for image. Using a simple Dockerfile instead to keep things simple.
=> Change upstream repo for pipeline-images/jenkins-2-centos7 image

index.d/pipeline-images.yaml
Both the containers are now under pipeline-images namespace.
=> Adds ccp-openshift-scan and ccp-openshift-slave in pipeline-images namespace

index.d/mattermost.yaml, index.d/pipeline-images.yaml
This is needed to make the new index ci go green.
Note PR will not go green until some other issues which are not directly in index are fixed.
=> Fixing errors in index based on strict new index ci.

index.d/dotnet.yaml
Dotnet 2.1 is now available on Centos, so we'd like to start building containers of it.
We should have a PR merged shortly updating the cccp.yml files in our s2i-dotnetcore repo to go along with this.
=> Add dotnet-21 container jobs

index.d/rhsyseng.yaml
Signed-off-by: Ruben Romero Montes <rromerom@redhat.com>
Fix https://github.com/RHsyseng/docker-rhel-elasticsearch/issues/46
=> Bump ES version to 5.6.10

index.d/mattermost.yaml
- Add new version for Mattermost Image - 5.1-PCP
- Reorganize file, group by image type
- Add comments on image purpose, type etc.
- Add note about retaining old images
=> Add Mattermost v5.1 and Clean up Mattermost Index file

index.d/mattermost.yaml
Release notes: https://docs.mattermost.com/administration/changelog.html#release-v5-2
Build directory: https://github.com/rhdt/mattermost-openshift/tree/master/5.2-PCP
=> Add Mattermost v5.2

index.d/openshift.yaml
* All the builds are getting stuck because of these images, temporarily commenting them out.
We need to fix this permanently later in new arch
=> Removing OpenShift images temporarily

index.d/navidshaikh.yaml, index.d/pipeline-images.yaml
and keeps it under navidshaikh namespace for time being to keep
the image around for failover.
=> Removes ccp-openshift-scan image from pipeline-images namespace

index.d/dharmit.yaml
In the new architecture of the service, we can easily build image based off our code and push it to internal registry so that dev/pre-prod deployments use that image instead. In fact, that's the best way to ensure that we use code that we're writing. So, this image is not longer needed to be build on r.c.o.
=> No need to build individual ccp-openshift-slave image anymore

index.d/mattermost.yaml
Bump mattermost versions
Changelogs available here: https://docs.mattermost.com/administration/changelog.html
Added the source repo folders via this PR: https://github.com/rhdt/mattermost-openshift/pull/26
=> Add mattermost v5.3 and v5.4

index.d/che-stacks.yaml
Related che PR https://github.com/eclipse/che-dockerfiles/pull/240
Related rh-che PR - https://github.com/redhat-developer/che-dockerfiles/pull/54
=> Adding 'centos-quarkus.io-jdk8' stack to container-index

index.d/centos.yaml
This commit deprecates these images:
* ror-41, ror-42 and ror-50
* ruby-22, ruby-23 and ruby-24
Adds images:
* nginx-116
* ruby-25 and ruby-26
=> Deprecates RoR and some NginX and Ruby containers

index.d/softwarefactory-project.yaml
It now depends on centos:8 instead of centos:7.
=> Update depends-on for dlrnapi container

index.d/centos.yaml
Some images are EOL like
postgresql-96, mongodb-34, mariadb-102 and python-36
@hhorak @pkubatrh Please look at it. I would be glad for review.
=> Deprecated EOL images since Oct 2020

index.d/centos.yaml
=> Deprecate PHP-7.2 and NGINX-1.14
